name: Release

on:
  workflow_run:
    workflows: [Run tests]
    types: [completed]
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - id: publish
        name: Release to NPM
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: beta
      - name: Tag successful release
        if: steps.publish.outputs.version != steps.publish.outputs.old-version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.publish.outputs.version }}
          message: 'Latest v${{ steps.publish.outputs.version }}'
